var golbal_var = (function(global,$){
	var modify_pass = function(mail_address,_id){
		var tpl = [];
		tpl.push("\n");
		tpl.push("<!---------------------------------------------------------修改密码-------------------------------------------------->\n");
		tpl.push("<form action='/update_pass' method='post'>");
		tpl.push("<input type='hidden' name='_id' value='"+_id+"'>");
		tpl.push("<div class=\"modify_pass\">\n");
		tpl.push("\n");
		tpl.push("<div class=\"form_item\">\n");
		tpl.push("<div class=\"form_label\">\n");
		tpl.push("<label>已绑定邮箱</label>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"form_cpt\">\n");
		tpl.push("<input type=\"text\" name=\"novel_name\" value=\""+mail_address+"\" disabled>\n");
		tpl.push("<button data-href=\"/send_mail?address="+mail_address+"\" href=\"javascript:void(0)\"id=\"valide_code\">发送验证码</button>\n");
		tpl.push("<script type=\"text/javascript\">\n");
		tpl.push("$(function(){\n");
		tpl.push("$('#valide_code').click(function(){\n");
		tpl.push("var that = $(this);\n");
		tpl.push("that.attr('disabled','disabled');\n");
		tpl.push("$.ajax({\n");
		tpl.push("url:$(this).data('href'),\n");
		tpl.push("success:function(data){\n");
		tpl.push("var true_code = data.code;//真确的验证码\n");
		tpl.push("var time = 20;\n");
		tpl.push("var timer = setInterval(function(){\n");
		tpl.push("that.text('重新发送验证码('+(time--)+')');\n");
		tpl.push("if(time == -1){\n");
		tpl.push("clearInterval(timer);\n");
		tpl.push("$.ajax({\n");
		tpl.push("url:'/quit_valide_code',\n");
		tpl.push("success:function(data){\n");
		tpl.push("console.log(data);\n");
		tpl.push("},\n");
		tpl.push("error:function(err){\n");
		tpl.push("alert('数据获取错误！');\n");
		tpl.push("}\n");
		tpl.push("})\n");
		tpl.push("that.text('重新发送验证码');\n");
		tpl.push("that.attr('disabled',false);\n");
		tpl.push("}\n");
		tpl.push("},1000);\n");
		tpl.push("\n");
		tpl.push("},\n");
		tpl.push("error:function(err){\n");
		tpl.push("alert('数据获取错误！');\n");
		tpl.push("}\n");
		tpl.push("})\n");
		tpl.push("});\n");
		tpl.push("});\n");
		tpl.push("</script>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"c_fix\"></div>\n");
		tpl.push("</div><!--form_item-->\n");
		tpl.push("\n");
		tpl.push("<div class=\"form_item\">\n");
		tpl.push("<div class=\"form_label\">\n");
		tpl.push("<label>验证码</label>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"form_cpt\">\n");
		tpl.push("<input type=\"text\" name=\"valide_code\" id=\"input_code\">\n");
		tpl.push("<button id=\"valide_code_1\">校验验证码</button>\n");
		tpl.push("<script type=\"text/javascript\">\n");
		tpl.push("$(function(){\n");
		tpl.push("$('#valide_code_1').click(function(e){\n");
		tpl.push("e.preventDefault();")
		tpl.push("var that = $(this);\n");
		tpl.push("$.ajax({\n");
		tpl.push("url:'/valide_code?valid='+$('#input_code').val(),\n");
		tpl.push("success:function(data){\n");
		tpl.push("if(parseInt(data.code) == 1){\n");
		tpl.push("$('.hide_area').css('display','block');\n");
		tpl.push("}else{\n");
		tpl.push("$.tips(undefined).setText('<div style=\"height:80px;line-height:80px;font-size:16px;\">验证码错误！</div>').resize(300,200).show();\n");
		tpl.push("return;\n");
		tpl.push("}\n");
		tpl.push("},\n");
		tpl.push("error:function(err){\n");
		tpl.push("alert('数据获取错误！');\n");
		tpl.push("}\n");
		tpl.push("});\n");
		tpl.push("})\n");
		tpl.push("});\n");
		tpl.push("</script>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"c_fix\"></div>\n");
		tpl.push("</div><!--form_item-->\n");
		tpl.push("<div class=\"hide_area\" style=\"display:none;\">\n");
		tpl.push("<div class=\"form_item\">\n");
		tpl.push("<div class=\"form_label\">\n");
		tpl.push("<label>新密码：</label>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"form_cpt\">\n");
		tpl.push("<input type=\"password\" name='n_password'>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"c_fix\"></div>\n");
		tpl.push("</div><!--form_item-->\n");
		tpl.push("\n");
		tpl.push("<div class=\"form_item\">\n");
		tpl.push("<div class=\"form_label\">\n");
		tpl.push("<label>确认密码：</label>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"form_cpt\">\n");
		tpl.push("<input type=\"password\" name='n_password1'>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"c_fix\"></div>\n");
		tpl.push("</div><!--form_item-->\n");
		tpl.push("</div>\n");
		tpl.push("\n");
		tpl.push("<div class=\"form_item\">\n");
		tpl.push("<div class=\"form_label\">\n");
		tpl.push("\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"form_cpt\">\n");
		tpl.push("\n");
		tpl.push("<button class=\"form_submit\" type=\"submit\">确认修改</button>\n");
		tpl.push("</div>\n");
		tpl.push("<div class=\"c_fix\"></div>\n");
		tpl.push("</div><!--form_item-->\n");
		tpl.push("</div>\n");
		tpl.push("</form>")
		tpl.push("<!---------------------------------------------------------修改密码-------------------------------------------------->\n");

		return tpl.join('');
	};

	return {
		modify_pass:modify_pass
	};
	
})(window,$);

